### ISSUE TITLE
Update membership description to 2018-2019 year

### ISSUE THREAD

**Issue by dannyqiu** [cornellacsu/old_website#11]
https://acsu.cornell.edu/join.html still references 2017-2018

<img width="851" alt="screen shot 2018-09-10 at 11 18 34 am" src="https://user-images.githubusercontent.com/1170755/45306703-4b649f80-b4eb-11e8-855b-c94a5740892a.png">

**Comment by xinyuzhao23** [comment]
https://github.com/cornellacsu/website/commit/94008ded86ae59752629f688bfdebb5aa773f002
