### ISSUE TITLE
Facebook link for G-body needs to be updated

### ISSUE THREAD

**Issue by tyleri** [cornellacsu/old_website#9]
https://facebook.com/events/2246520265581631

https://acsu.cornell.edu/join.html

**Comment by xinyuzhao23** [comment]
It's updated on the actual website. I'll transfer over the change soon.

**Comment by xinyuzhao23** [comment]
https://github.com/cornellacsu/website/commit/94008ded86ae59752629f688bfdebb5aa773f002
